# Generated by Django 4.2.23 on 2025-09-18 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_uuid_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='receive_marketing_emails',
        ),
    ]
