# Generated by Django 4.2.23 on 2025-09-02 12:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('theater_name', models.CharField(default='Main Theater', max_length=100)),
                ('screen_number', models.PositiveIntegerField(default=1)),
                ('total_seats', models.PositiveIntegerField(default=100)),
                ('available_seats', models.PositiveIntegerField(default=100)),
                ('ticket_price', models.DecimalField(decimal_places=2, help_text='Ticket price in dollars', max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies.movie')),
            ],
            options={
                'ordering': ['datetime', 'theater_name', 'screen_number'],
                'unique_together': {('theater_name', 'screen_number', 'datetime')},
            },
        ),
    ]
