# Generated by Django 4.2.23 on 2025-09-03 17:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_showtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('total_screens', models.PositiveIntegerField(default=1)),
                ('parking_available', models.BooleanField(default=True)),
                ('accessibility_features', models.TextField(blank=True, help_text='Describe accessibility features')),
                ('amenities', models.TextField(blank=True, help_text='List amenities like concessions, IMAX, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='showtime',
            options={'ordering': ['datetime', 'theater__name', 'screen_number']},
        ),
        migrations.AlterUniqueTogether(
            name='showtime',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='showtime',
            name='theater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies.theater'),
        ),
        migrations.AlterUniqueTogether(
            name='showtime',
            unique_together={('theater', 'screen_number', 'datetime')},
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='theater_name',
        ),
    ]
