# Generated by Django 4.2.23 on 2025-09-03 17:54

from django.db import migrations


def create_default_theater(apps, schema_editor):
    """Create a default theater for existing showtimes."""
    Theater = apps.get_model('movies', 'Theater')
    
    # Create a default theater if none exists
    default_theater, created = Theater.objects.get_or_create(
        name="Main Theater",
        defaults={
            'address': '123 Main Street',
            'city': 'Los Angeles',
            'state': 'CA',
            'zip_code': '90210',
            'phone_number': '+1-555-0123',
            'total_screens': 5,
            'parking_available': True,
            'accessibility_features': 'Wheelchair accessible, Audio description available',
            'amenities': 'Dolby Atmos, Concession stand',
            'is_active': True
        }
    )
    
    # Update all showtimes without a theater to use this default
    Showtime = apps.get_model('movies', 'Showtime')
    Showtime.objects.filter(theater__isnull=True).update(theater=default_theater)


def reverse_create_default_theater(apps, schema_editor):
    """Reverse migration - remove default theater if no other theaters exist."""
    Theater = apps.get_model('movies', 'Theater')
    # Only remove the default theater if it's the only one
    if Theater.objects.count() == 1:
        Theater.objects.filter(name="Main Theater").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_theater_alter_showtime_options_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_theater, reverse_create_default_theater),
    ]
