# Generated by Django 4.2.23 on 2025-09-03 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20250903_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies.theater'),
        ),
    ]
