# Generated by Django 4.2.23 on 2025-09-03 18:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('movies', '0005_alter_showtime_theater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, help_text='Base ticket price in dollars', max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.CreateModel(
            name='SeatLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('screen_number', models.PositiveIntegerField()),
                ('name', models.CharField(help_text="Layout name (e.g., 'Standard', 'IMAX', 'Premium')", max_length=100)),
                ('total_rows', models.PositiveIntegerField()),
                ('total_seats', models.PositiveIntegerField()),
                ('row_configuration', models.JSONField(help_text="JSON configuration of seats per row, e.g., {'A': 12, 'B': 14, 'C': 16}")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_layouts', to='movies.theater')),
            ],
            options={
                'ordering': ['theater__name', 'screen_number'],
                'unique_together': {('theater', 'screen_number')},
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row', models.CharField(help_text="Seat row (e.g., 'A', 'B', 'C')", max_length=2)),
                ('number', models.PositiveIntegerField(help_text='Seat number within the row')),
                ('seat_type', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('accessible', 'Accessible'), ('couple', 'Couple Seat'), ('blocked', 'Blocked/Maintenance')], default='standard', max_length=20)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Price multiplier for this seat type (1.0 = base price, 1.5 = 50% premium)', max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seat_layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.seatlayout')),
            ],
            options={
                'ordering': ['row', 'number'],
                'unique_together': {('seat_layout', 'row', 'number')},
            },
        ),
        migrations.AddField(
            model_name='showtime',
            name='seat_layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies.seatlayout'),
        ),
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='reserved', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='Temporary reservation expires after this time')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to='bookings.booking')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='movies.seat')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to='movies.showtime')),
            ],
            options={
                'ordering': ['showtime__datetime', 'seat__row', 'seat__number'],
                'unique_together': {('showtime', 'seat')},
            },
        ),
    ]
